name: Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: Target Platform
        required: true
        default: StandaloneOSX
        type: choice
        options:
          - StandaloneOSX
          - StandaloneWindows64

jobs:
  build:
    name: Build for ${{ inputs.platform }}
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ inputs.platform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ inputs.platform }}-
            Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.SECRET_TOKEN }}
          targetPlatform: ${{ inputs.platform }}
          unityVersion: 2022.3.50f1

      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ inputs.platform }}
          path: build/${{ inputs.platform }}
